openapi: 3.1.0
x-stoplight:
  id: onjz61nq1ubck
info:
  title: Gemini1_5Flash
  version: '1.0'
servers:
  - url: 'https://generativelanguage.googleapis.com/'
    description: ''
paths:
  '/v1beta/models/gemini-1.5-flash:generateContent':
    post:
      summary: Generate content
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  candidates:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: object
                          properties:
                            parts:
                              type: array
                              items:
                                type: object
                                properties:
                                  text:
                                    type: string
                            role:
                              type: string
                        finishReason:
                          type: string
                        index:
                          type: integer
                        safetyRatings:
                          type: array
                          items:
                            type: object
                            properties:
                              category:
                                type: string
                              probability:
                                type: string
                  usageMetadata:
                    type: object
                    properties:
                      promptTokenCount:
                        type: integer
                      candidatesTokenCount:
                        type: integer
                      totalTokenCount:
                        type: integer
                x-examples:
                  Example 1:
                    candidates:
                      - content:
                          parts:
                            - text: ''
                          role: model
                        finishReason: STOP
                        index: 0
                        safetyRatings:
                          - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
                            probability: NEGLIGIBLE
                    usageMetadata:
                      promptTokenCount: 17
                      candidatesTokenCount: 639
                      totalTokenCount: 656
      operationId: 'post-v1beta-models-gemini-1.5-flash:generateContent'
      x-stoplight:
        id: p677op075h66d
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  contents:
                    - parts:
                        - text: ''
              properties:
                contents:
                  type: array
                  items:
                    type: object
                    required:
                      - parts
                    properties:
                      parts:
                        type: array
                        items:
                          type: object
                          required:
                            - text
                          properties:
                            text:
                              type: string
                              description: AI Prompt text
    parameters:
      - schema:
          type: string
        in: query
        name: key
        description: API Key
components:
  schemas: {}
x-internal: true
